version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8876:80"
    depends_on:
        - app
    container_name: stream-nginx

  app:
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
        - db
    container_name: stream-app

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stream_db
      UPLOAD_LIMIT: 500M
      MYSQL_USER: roman
      MYSQL_PASSWORD: pass
    ports:
      - "8101:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: stream-db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
        - 8102:80
    environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: root
    container_name: stream-phpmyadmin

